// Date: 2013.11.14. 15:56:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer CraftingBottom;
    ModelRenderer CraftingBotSlab;
    ModelRenderer Pillar;
    ModelRenderer WorkbenchSlab;
    ModelRenderer WorkbenchTop;
    ModelRenderer Shape1;
  
  public ModelNew()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      CraftingBottom = new ModelRenderer(this, 0, 0);
      CraftingBottom.addBox(0F, 0F, 0F, 16, 2, 16);
      CraftingBottom.setRotationPoint(-8F, 22F, -8F);
      CraftingBottom.setTextureSize(128, 64);
      CraftingBottom.mirror = true;
      setRotation(CraftingBottom, 0F, 0F, 0F);
      CraftingBotSlab = new ModelRenderer(this, 0, 18);
      CraftingBotSlab.addBox(0F, 0F, 0F, 14, 1, 14);
      CraftingBotSlab.setRotationPoint(-7F, 21F, -7F);
      CraftingBotSlab.setTextureSize(128, 64);
      CraftingBotSlab.mirror = true;
      setRotation(CraftingBotSlab, 0F, 0F, 0F);
      Pillar = new ModelRenderer(this, 0, 33);
      Pillar.addBox(0F, 0F, 0F, 12, 10, 12);
      Pillar.setRotationPoint(-6F, 11F, -6F);
      Pillar.setTextureSize(128, 64);
      Pillar.mirror = true;
      setRotation(Pillar, 0F, 0F, 0F);
      WorkbenchSlab = new ModelRenderer(this, 0, 18);
      WorkbenchSlab.addBox(0F, 0F, 0F, 14, 1, 14);
      WorkbenchSlab.setRotationPoint(-7F, 10F, -7F);
      WorkbenchSlab.setTextureSize(128, 64);
      WorkbenchSlab.mirror = true;
      setRotation(WorkbenchSlab, 0F, 0F, 0F);
      WorkbenchTop = new ModelRenderer(this, 64, 0);
      WorkbenchTop.addBox(0F, 0F, 0F, 16, 2, 16);
      WorkbenchTop.setRotationPoint(-8F, 8F, -8F);
      WorkbenchTop.setTextureSize(128, 64);
      WorkbenchTop.mirror = true;
      setRotation(WorkbenchTop, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      Shape1.setRotationPoint(0F, 6F, 0F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    CraftingBottom.render(f5);
    CraftingBotSlab.render(f5);
    Pillar.render(f5);
    WorkbenchSlab.render(f5);
    WorkbenchTop.render(f5);
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
